---
- hosts: pi
  tasks:
    - name: Update all packages to their lastet version
      apt:
        name: "*"
        state: latest
    - name: Upgrade the OS (apt-get dist_upgrade)
      apt:
        upgrade: dist
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Only run "update_cache=yes" id the last one is more than 3600 secs ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
